-- MySQL Script generated by MySQL Workbench
-- Mon 24 Sep 2018 12:41:51 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_entregue
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_entregue
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_entregue` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci ;
USE `db_entregue` ;

-- -----------------------------------------------------
-- Table `db_entregue`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_entregue`.`usuario` ;

CREATE TABLE IF NOT EXISTS `db_entregue`.`usuario` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `cadastrante_id` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_cadastrante_idx` (`cadastrante_id` ASC),
  CONSTRAINT `fk_usuario_cadastrante`
    FOREIGN KEY (`cadastrante_id`)
    REFERENCES `db_entregue`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entregue`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_entregue`.`cliente` ;

CREATE TABLE IF NOT EXISTS `db_entregue`.`cliente` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cnpj_cpf` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(50) NOT NULL,
  `celular` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cadastrante_id` BIGINT(20) NOT NULL,
  `proprietario_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_criador_idx` (`cadastrante_id` ASC),
  INDEX `fk_cliente_proprietario_idx` (`proprietario_id` ASC),
  CONSTRAINT `fk_cliente_cadastrante`
    FOREIGN KEY (`cadastrante_id`)
    REFERENCES `db_entregue`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_proprietario`
    FOREIGN KEY (`proprietario_id`)
    REFERENCES `db_entregue`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entregue`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_entregue`.`categoria` ;

CREATE TABLE IF NOT EXISTS `db_entregue`.`categoria` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entregue`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_entregue`.`produto` ;

CREATE TABLE IF NOT EXISTS `db_entregue`.`produto` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL COMMENT 'Unidade, Peso',
  `estoque` BIGINT(20) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `imagem` BLOB NULL,
  `categoria_id` BIGINT(20) NOT NULL,
  `proprietario_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categoria_idx` (`categoria_id` ASC),
  INDEX `fk_usuario_idx` (`proprietario_id` ASC),
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `db_entregue`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_usuario`
    FOREIGN KEY (`proprietario_id`)
    REFERENCES `db_entregue`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entregue`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_entregue`.`endereco` ;

CREATE TABLE IF NOT EXISTS `db_entregue`.`endereco` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cep` INT(8) NOT NULL,
  `rua` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(255) NOT NULL,
  `complemento` VARCHAR(255) NOT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cliente_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_endereco_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `db_entregue`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entregue`.`forma_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_entregue`.`forma_pagamento` ;

CREATE TABLE IF NOT EXISTS `db_entregue`.`forma_pagamento` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entregue`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_entregue`.`pedido` ;

CREATE TABLE IF NOT EXISTS `db_entregue`.`pedido` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `total` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `cliente_id` BIGINT(20) NOT NULL,
  `cadastrante_id` BIGINT(20) NOT NULL,
  `proprietario_id` BIGINT(20) NOT NULL,
  `endereco_entrega_id` BIGINT(20) NOT NULL,
  `forma_pagamento_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_id_idx` (`cliente_id` ASC),
  INDEX `fk_usuario_idx` (`cadastrante_id` ASC),
  INDEX `fk_endereco_entrega_idx` (`endereco_entrega_id` ASC),
  INDEX `fk_pedido_forma_pagamento_idx` (`forma_pagamento_id` ASC),
  INDEX `fk_pedido_proprietario_idx` (`proprietario_id` ASC),
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `db_entregue`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_cadastrante`
    FOREIGN KEY (`cadastrante_id`)
    REFERENCES `db_entregue`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_endereco_entrega`
    FOREIGN KEY (`endereco_entrega_id`)
    REFERENCES `db_entregue`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_forma_pagamento`
    FOREIGN KEY (`forma_pagamento_id`)
    REFERENCES `db_entregue`.`forma_pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_proprietario`
    FOREIGN KEY (`proprietario_id`)
    REFERENCES `db_entregue`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entregue`.`pedido_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_entregue`.`pedido_item` ;

CREATE TABLE IF NOT EXISTS `db_entregue`.`pedido_item` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `quantidade` INT(10) NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  `desconto` DECIMAL(10,2) NOT NULL,
  `incluido_em` DATETIME NOT NULL,
  `pedido_id` BIGINT(20) NOT NULL,
  `produto_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_idx` (`pedido_id` ASC),
  INDEX `fk_produto_idx` (`produto_id` ASC),
  CONSTRAINT `fk_pedido_item_pedido`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `db_entregue`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_item_produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `db_entregue`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entregue`.`permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_entregue`.`permissao` ;

CREATE TABLE IF NOT EXISTS `db_entregue`.`permissao` (
  `id` BIGINT(20) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entregue`.`usuario_permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_entregue`.`usuario_permissao` ;

CREATE TABLE IF NOT EXISTS `db_entregue`.`usuario_permissao` (
  `usuario_id` BIGINT(20) NOT NULL,
  `permissao_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`usuario_id`, `permissao_id`),
  INDEX `fk_usuario_permissao_permissao_idx` (`permissao_id` ASC),
  CONSTRAINT `fk_usuario_permissao_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_entregue`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_permissao_permissao`
    FOREIGN KEY (`permissao_id`)
    REFERENCES `db_entregue`.`permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
